---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/kubedoo-lonelynode/infrastructure/envoy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: envoy-gateway-system