---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-secrets-op
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/kubedoo-lonelynode/infrastructure/vault-secrets-op
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: vault-secrets-op