---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vault-secrets-op
  namespace: vault-secrets-op
spec:
  interval: 10m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-op
  namespace: vault-secrets-op
spec:
  interval: 10m
  chart:
    spec:
      chart: vault-secrets-operator
      version: ">=0.4.3 <0.5"
      sourceRef:
        kind: HelmRepository
        name: vault-secrets-op
        namespace: vault-secrets-op
      interval: 10m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  name: default
  namespace: vault-secrets-op
spec:
  organizationID: 99c837bc-5c41-4547-be96-af1367af26d6
  projectID: aa5797fb-5ef6-4b6e-a95b-6974f49133e1
  servicePrincipal:
    secretRef: hcp-vso-serviceprincipal