---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vault-secrets-op
  namespace: kube-system
spec:
  interval: 10m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-op
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: vault-secrets-operator
      version: ">=0.4.3 <0.5"
      sourceRef:
        kind: HelmRepository
        name: vault-secrets-op
        namespace: kube-system
      interval: 10m