---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: envoy
  namespace: envoy-gateway-system
spec:
  interval: 10m0s
  type: oci
  url: oci://docker.io/envoyproxy/gateway-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: envoy
  namespace: envoy-gateway-system
spec:
  interval: 10m
  chart:
    spec:
      chart: eg
      version: ">=0.6.0 <0.7.0"
      sourceRef:
        kind: HelmRepository
        name: envoy
        namespace: envoy-gateway-system
      interval: 10m