---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: hcp-vso-secret
  namespace: cert-manager
spec:
  appName: cert-manager-bootstrap
  destination:
    create: true
    labels:
      hvs: "true"
    name: hcp-cert-manager-bootstrap-authsp
  refreshAfter: 1h
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ideal.tea7306@thenigh.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-bootstrap
            key: cloudflare_access
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ideal.tea7306@thenigh.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-bootstrap
            key: cloudflare_access
